version: '3.8'
services:
  frontend:
    container_name: frontend-server
    build:
      context: ./client 
      dockerfile: Dockerfile
    ports:
      - "3001:80" # Map TCP traffic from port 80 on the host to port 80 in the container
    networks:
      - app-network
    restart: always

  backend:
    container_name: backend-server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - DOCKER_ENV=true
      - MONGO_URI=mongodb://mongo:27017/myDatabase
      - JWT_SECRET=secret
    ports:
      - "5001:5001"
    depends_on:
      - mongo
      #- frontend
    command: /bin/sh -c "node createAdmin.js && node index.js"
    networks:
      - app-network
    restart: always

  mongo:
    container_name: mongo-server
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017" # Optional: expose this port to access MongoDB directly if needed
    networks:
      - app-network
    restart: always

volumes:
  mongo-data: # Persistent volume for MongoDB data

networks:
  app-network:
    name: app-network
    driver: bridge

